import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css',
})
export class ContactComponent {
  students: any[] = [
    {
      Id: 1,
      Name: 'Amit Kumar',
      rollno: '2021001',
      address: 'Delhi, India',
      Gender: 'Female',
      Marks: 45,
      status: false,
    },
    {
      Id: 2,
      Name: 'Priya Sharma',
      rollno: '2021002',
      address: 'Mumbai, India',
      Gender: 'Male',
      Marks: 98,
      status: true,
    },
    {
      Id: 3,
      Name: 'Rahul Singh',
      rollno: '2021003',
      address: 'Bangalore, India',
      Gender: 'Female',
      Marks: 57,
      status: false,
    },
    {
      Id: 4,
      Name: 'Anjali Gupta',
      rollno: '2021004',
      address: 'Kolkata, India',
      Gender: 'Male',
      Marks: 90,
      status: false,
    },
    {
      Id: 5,
      Name: 'Vikram Patel',
      rollno: '2021005',
      address: 'Chennai, India',
      Gender: 'Male',
      Marks: 79,
      status: false,
    },
    {
      Id: 6,
      Name: 'Neha Verma',
      rollno: '2021006',
      address: 'Hyderabad, India',
      Gender: 'Female',
      Marks: 88,
      status: true,
    },
    {
      Id: 7,
      Name: 'Rajesh Kumar',
      rollno: '2021007',
      address: 'Pune, India',
      Gender: 'Male',
      Marks: 75,
      status: false,
    },
    {
      Id: 8,
      Name: 'Sneha Singhania',
      rollno: '2021008',
      address: 'Jaipur, India',
      Gender: 'Male',
      Marks: 35,
      status: false,
    },
    {
      Id: 9,
      Name: 'Arjun Mishra',
      rollno: '2021009',
      address: 'Ahmedabad, India',
      Gender: 'Female',
      Marks: 85,
      status: false,
    },
    {
      Id: 10,
      Name: 'Kavita Reddy',
      rollno: '2021010',
      address: 'Lucknow, India',
      Gender: 'Male',
      Marks: 45,
      status: true,
    },
  ];
}
